server {
    listen       80;
    root         /usr/share/nginx/html;
    index        index.html;

    location /v1/ {
        proxy_pass http://ppanel.ppanel.svc.cluster.local:8080;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
